# Generated by Django 3.2.5 on 2021-08-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_rename_type_rate_currency_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.PositiveSmallIntegerField(max_length=3)),
                ('path', models.CharField(max_length=255)),
                ('response_time', models.PositiveSmallIntegerField()),
                ('request_method', models.CharField(max_length=10)),
            ],
        ),
    ]
