# Generated by Django 3.2.5 on 2021-08-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_responselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='request_method',
            field=models.CharField(choices=[('get', 'GET'), ('post', 'POST')], max_length=10),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='response_time',
            field=models.PositiveSmallIntegerField(help_text='im milliseconds'),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='status_code',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
